inherit_from: .rubocop_todo.yml

AllCops:
  AllowSymlinksInCacheRootDirectory: true
  Exclude:
    - spec/**/*
    - tmp/**/*

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'ya_kansuji.gemspec' # Required to support 2.0

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/AndOr:
  EnforcedStyle: conditionals

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/PerlBackrefs:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed

Layout/IndentHeredoc:
  Enabled: false # Disable for ruby 2.0...

# Configuration parameters: EnforcedStyle, SingleLineConditionsOnly, IncludeTernaryExpressions.
# SupportedStyles: assign_to_condition, assign_inside_condition
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

# Offense count: 1
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 94

Style/FormatString:
  EnforcedStyle: percent


Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
