---
sudo: false
language: ruby
cache: bundler
rvm:
  - jruby-9.1
  - jruby
  - "2.0.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
  - ruby-head
before_install:
  - type bundle || gem install bundler
